"""Isolated API integration checks. Run: python tests/test_api.py"""
import sys,sqlite3,json,time
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
import server
from fastapi.testclient import TestClient
server.DB=sqlite3.connect(':memory:',check_same_thread=False)
server.DB.execute('CREATE TABLE rooms(code TEXT PRIMARY KEY,owner TEXT,data TEXT)')
server.DB.execute('CREATE TABLE history(id TEXT PRIMARY KEY,owner TEXT,data TEXT)')
host=TestClient(server.app);guest=TestClient(server.app);stranger=TestClient(server.app)
b=host.get('/api/bootstrap').json();room=b['room'];url='/api/room/'+room
checks=0
def check(cond,msg):
 global checks
 assert cond,msg
 checks+=1;print('PASS',msg)
def action(a,**kw):
 res=host.post(url+'/action',json={'action':a,**kw});assert res.status_code==200,res.text;return res.json()
check(len(b['state']['bank'])==100,'100 seed questions loaded')
check(len(b['state']['board'])==30,'balanced 30-question default board')
check(all(t['score']==0 for t in b['state']['teams']),'scores start at zero')
check(stranger.post(url+'/action',json={'action':'adjust','amount':9999}).status_code==403,'guest cannot modify scores')
check(stranger.get(url+'/export').status_code==403,'guest cannot export answers')
check('bank' not in stranger.get(url+'/public').json(),'public state excludes private bank')
check(guest.post(url+'/join',json={'name':'Test Player','team':'0'}).status_code==200,'participant joins')
me=guest.get(url+'/public').json()['me'];check(guest.post(url+'/join',json={'name':'New identity','team':'1'}).json()=={'ok':True},'existing cookie cannot rejoin as a new identity')
check(guest.get(url+'/public').json()['me']['id']==me['id'],'identity persists')
host.post(url+'/settings',json={'settings':{'doubleChance':0}})
s=action('select',id='architects-1')
p=guest.get(url+'/public').json()
check('correctAnswer' not in p['current'] and 'explanation' not in p['current'],'answer and explanation withheld before reveal')
check(s['current']['correctAnswer']=='Frank Lloyd Wright','host can inspect answer')
check(guest.post(url+'/answer',json={'answer':'Frank Lloyd Wright'}).status_code==200,'on-time answer accepted')
check(guest.post(url+'/answer',json={'answer':'Frank Gehry'}).status_code==400,'duplicate submission rejected')
check(guest.get(url+'/public').json()['me']['score']==0,'answer not scored until reveal')
s=action('correct');check(s['teams'][0]['score']==100,'host correct awards 100')
p=guest.get(url+'/public').json();check(p['me']['score']==100,'audience answer earns 100 after reveal')
check(p['current']['correctAnswer']=='Frank Lloyd Wright','answer released after reveal')
check(host.post(url+'/action',json={'action':'correct'}).status_code==400,'question cannot be awarded twice')
check(guest.post(url+'/answer',json={'answer':'Frank Lloyd Wright'}).status_code==400,'revealed question rejects late answers')
action('board');check(host.post(url+'/action',json={'action':'select','id':'architects-1'}).status_code==400,'used question cannot be replayed')
action('select',id='architects-2');action('pause');check(guest.post(url+'/answer',json={'answer':'Zaha Hadid'}).status_code==400,'paused timer rejects answers')
action('pause');action('wrong');s=action('correct');check(s['teams'][1]['score']==100,'steal awards 50 percent of 200')
s=action('board');action('select',id=next(q['id'] for q in s['board'] if q['category']=='architects' and q['difficulty']==3))
o,r=server.load(room);r['current']['deadline']=time.time()-1;server.save(r,o)
check(guest.post(url+'/answer',json={'answer':'anything'}).status_code==400,'server rejects answers after deadline')
action('board');action('adjust',team='0',amount=900);action('final')
check(guest.post(url+'/wager',json={'amount':1001}).status_code==400,'wager cannot exceed score')
check(guest.post(url+'/wager',json={'amount':500}).status_code==200,'captain locks valid wager')
check(guest.post(url+'/wager',json={'amount':100}).status_code==400,'locked wager cannot change')
p=guest.get(url+'/public').json();check('wagers' not in p,'wager amounts hidden from public')
for t in ['1','2','3']:check(host.post(url+'/wager',json={'team':t,'amount':0}).status_code==200,'host locks offline team wager '+t)
action('finalStart');action('reveal')
for t in ['0','1','2','3']:action('finalJudge',team=t,correct=True)
s=action('end');check(s['teams'][0]['score']==1500,'final wager applied exactly once')
check(len(host.get('/api/history').json())==1,'completed game saved')
check(host.get('/api/history').json()[0]['rounds'][0]['responses'][me['id']]['correct'] is True,'question-level audience performance saved')
check(host.post(url+'/action',json={'action':'end'}).status_code==400,'duplicate history save rejected')
key=host.get('/api/recovery').json()['key'];check(stranger.post('/api/recovery',json={'key':key}).status_code==200,'host recovery restores access')
check('bank' in stranger.get(url).json(),'recovered host has private access')
check(host.post(url+'/action',json={'action':'reset'},headers={'Origin':'https://evil.example'}).status_code==403,'cross-origin mutations rejected')
action('reset');s=host.get(url).json();check(s['participants']==0 and not s['used'] and all(t['score']==0 for t in s['teams']),'reset clears players, question progress, and scores')
check(len(host.get('/api/history').json())==1,'reset preserves completed history')
# CRUD + timer + edited final
q=dict(s['bank'][0],id='',question='Test custom question',correctAnswer='A',options=['A','B','C','D'],timeLimit=15)
r=host.post(url+'/question',json={'question':q});check(r.status_code==200,'question creation works')
qnew=next(q for q in r.json()['bank'] if q['question']=='Test custom question')
check(qnew['customTimer'] is True,'custom question timer saved')
check(host.post(url+'/question',json={'id':qnew['id'],'delete':True}).status_code==200,'question deletion works')
f=dict(s['finalQuestion'],question='Custom final prompt');check(host.post(url+'/question',json={'question':f}).status_code==200,'final prompt editable')
check(host.get(url).json()['finalQuestion']['question']=='Custom final prompt','edited final persisted')
print(f'\n{checks} checks passed.')
